  # KMS Key for EC2 EBS Volume Encryption
  NodeKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS Key for EKS Worker Node EBS Volume Encryption"
      KeyUsage: ENCRYPT_DECRYPT
      EnableKeyRotation: true
      PendingWindowInDays: 7
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-node-kms-key"
        - Key: StackId
          Value: !Ref AWS::StackId
        - Key: StackName
          Value: !Ref AWS::StackName
        - Key: SCE:owner
          Value: CET
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: AllowEC2RoleUseOfTheKey
            Effect: Allow
            Principal:
              AWS: !GetAtt EKSRole.Arn
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"

  NodeKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ClusterName}-node-kms-key"
      TargetKeyId: !Ref NodeKmsKey

  # Launch Template with KMS Encryption for EBS Volumes
  NodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Sub "{{resolve:ssm:/aws/service/eks/optimized-ami/1.24/amazon-linux-2/recommended/image_id}}"
        InstanceType: t3.medium
        KeyName: !Ref KeyName  # Define your KeyPair if needed for SSH access
        SecurityGroupIds:
          - !Ref EKSClusterSecurityGroup
        MetadataOptions:
          HttpTokens: required  # Enforce IMDSv2
          HttpPutResponseHopLimit: 2
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              Encrypted: true
              KmsKeyId: !Ref NodeKmsKey  # Attach KMS key to encrypt the EBS volume
              VolumeSize: 20  # Size of EBS volume in GiB
              VolumeType: gp3  # You can use gp3, gp2, io1, etc.
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            /etc/eks/bootstrap.sh ${ClusterName}
