trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
  - repository: commonScripts
    type: git
    name: CloudEngineering/SCE-Common
    ref: main

parameters:
  - name: clusterName
    displayName: Cluster Name
    type: string
    default: '-'
    values:
      - "-"
      - LC-spoke
      - Sandpit-APIC-Gateway

stages:

  - stage: Deploy
    condition: not(eq('${{parameters.clusterName}}', '-'))
    dependsOn: []
    jobs:
    - template: template-on-prem.yml
      parameters:
        clusterName: ${{ parameters.clusterName }}
        serviceConnection: sce-automationaccount-assumeall
