OIDCProvider:
  Type: "AWS::IAM::OIDCProvider"
  Properties: 
    Url: !GetAtt EKSCluster.OIDC.Issuer
    ClientIdList: 
      - "sts.amazonaws.com"
    ThumbprintList: 
      - "9e99a48a9960b14926bb7f3b02e22da0cedef055" # Common AWS OIDC thumbprint
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSClusterSecurityGroup
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
          - !Ref Subnet3
      RoleArn: !GetAtt EKSRole.Arn

  GetOIDCProviderFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          import boto3

          def handler(event, context):
              eks = boto3.client('eks')
              cluster_name = event['ClusterName']
              response = eks.describe_cluster(name=cluster_name)
              return {'OidcIssuer': response['cluster']['identity']['oidc']['issuer']}
      Handler: index.handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn

  CustomOIDCProvider:
    Type: Custom::GetOIDCProvider
    Properties:
      ServiceToken: !GetAtt GetOIDCProviderFunction.Arn
      ClusterName: !Ref ClusterName

  OIDCProvider:
    Type: "AWS::IAM::OIDCProvider"
    Properties: 
      Url: !GetAtt CustomOIDCProvider.OidcIssuer
      ClientIdList: 
        - "sts.amazonaws.com"
      ThumbprintList: 
        - "<OIDC_PROVIDER_THUMBPRINT>"

Outputs:
  OIDCProviderURL:
    Description: OIDC Provider URL
    Value: !GetAtt CustomOIDCProvider.OidcIssuer
